# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=12)),
                ('flavors', models.CharField(max_length=50)),
                ('toppings', models.CharField(max_length=50)),
                ('container', models.CharField(max_length=50)),
                ('order_time', models.DateTimeField(blank=True)),
            ],
        ),
    ]
