# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/options')),
                ('group', models.CharField(choices=[('flavor', 'Flavor'), ('topping', 'Topping'), ('container', 'Container')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Container',
        ),
        migrations.DeleteModel(
            name='Flavor',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
