# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='flavors',
            new_name='flavor',
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
