# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0002_auto_20160606_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavors', models.CharField(max_length=50)),
                ('toppings', models.CharField(max_length=50)),
                ('containers', models.CharField(max_length=50)),
            ],
        ),
    ]
