# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0003_auto_20160617_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='container',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='flavor',
            old_name='flavor',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='topping',
            new_name='name',
        ),
    ]
