# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0004_auto_20160617_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ice_cream.Container'),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='flavor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ice_cream.Flavor'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='toppings',
        ),
        migrations.AddField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='ice_cream.Topping'),
        ),
    ]
