# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 18:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0005_auto_20160607_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlavorImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/flavor_pics')),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ice_cream.Flavor')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='toppings',
            field=models.CharField(max_length=500),
        ),
    ]
