# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-08 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ice_cream', '0007_auto_20160608_1914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='containers',
            new_name='container',
        ),
        migrations.RenameField(
            model_name='flavor',
            old_name='flavors',
            new_name='flavor',
        ),
        migrations.RenameField(
            model_name='topping',
            old_name='toppings',
            new_name='topping',
        ),
        migrations.AlterField(
            model_name='flavor',
            name='image',
            field=models.ImageField(upload_to='static/images/flavors'),
        ),
    ]
